//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAR_FROM_HOME.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIODT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIODT()
        {
            this.PUBLICACIONDT = new HashSet<PUBLICACIONDT>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USU_RED { get; set; }
        public string RED { get; set; }
        public string MAIL { get; set; }
        public Nullable<int> N_CELULAR { get; set; }
        public string FOTO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUBLICACIONDT> PUBLICACIONDT { get; set; }
    }
}
